apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-secret-generator
  namespace: mongo
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: secret-gen
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              if ! kubectl get secret mongo-credentials -n mongo >/dev/null 2>&1; then
                user=$(openssl rand -hex 4)
                pass=$(openssl rand -hex 8)
                kubectl create secret generic mongo-credentials -n mongo \
                  --from-literal=MONGO_INITDB_ROOT_USERNAME=$user \
                  --from-literal=MONGO_INITDB_ROOT_PASSWORD=$pass
              fi


