apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-generator-rb
  namespace: emailsys
subjects:
  - kind: ServiceAccount
    name: secret-generator-sa
    namespace: emailsys
roleRef:
  kind: Role
  name: secret-generator-role
  apiGroup: rbac.authorization.k8s.io
