apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mautic-pvc
  namespace: emailsys
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
