apiVersion: batch/v1
kind: Job
metadata:
  name: opensearch-secret-generator
  namespace: opensearch
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: secret-gen
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              if ! kubectl get secret opensearch-credentials -n opensearch >/dev/null 2>&1; then
                user=admin
                pass=$(openssl rand -hex 8)
                kubectl create secret generic opensearch-credentials -n opensearch \
                  --from-literal=username=$user \
                  --from-literal=password=$pass
              fi
