apiVersion: batch/v1
kind: Job
metadata:
  name: opensearch-secret-generator
  namespace: opensearch
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: secret-gen
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              if ! kubectl get secret opensearch-credentials -n opensearch >/dev/null 2>&1; then
                user="admin$(openssl rand -hex 2)"
                pass=$(openssl rand -hex 12)
                kubectl create secret generic opensearch-credentials -n opensearch \
                  --from-literal=username=$user \
                  --from-literal=password=$pass
                echo "✅ Secret 'opensearch-credentials' created with random credentials."
              else
                echo "ℹ️ Secret already exists, skipping creation."
              fi
