apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu
spec:
  template:
    spec:
      nodeSelector:
        role: email-node
      containers:
        - name: mailu
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
