apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautic
spec:
  template:
    spec:
      nodeSelector:
        role: email1
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z mysql 3306; do
                echo "Waiting for MySQL..."
                sleep 2
              done
      containers:
        - name: mautic
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
