apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v16
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
    ssl: true
  storage:
    useAllNodes: false
    nodes:
      - name: "nvme"
        devices:
          - name: "*"
      - name: "ssd"
        devices:
          - name: "*"
    pools:
      - name: nvme-pool
        replicated:
          size: 1
      - name: ssd-pool
        replicated:
          size: 1
