apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v16
  dataDirHostPath: /var/lib/rook

  # MON / MGR / Dashboard על master2 בלבד
  mon:
    count: 1
    allowMultiplePerNode: false
  placement:
    mgr:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - master2
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

    dashboard:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - master2
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

  dashboard:
    enabled: true
    ssl: true

  storage:
    useAllNodes: false
    nodes:
      - name: "nyssdbig1"
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                  - storge
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
        devices:
          - name: "*"

    pools:
      - name: mongo-pool
        replicated:
          size: 1
        failureDomain: host
        crushRoot: default

      - name: mysql-pool
        replicated:
          size: 1
        failureDomain: host
        crushRoot: default

      - name: opensearch-pool
        replicated:
          size: 1
        failureDomain: host
        crushRoot: default
