apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-secret-generator
  namespace: kafka
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: secret-gen
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              if ! kubectl get secret kafka-credentials -n kafka >/dev/null 2>&1; then
                user=$(openssl rand -hex 4)
                pass=$(openssl rand -hex 8)
                kubectl create secret generic kafka-credentials -n kafka \
                  --from-literal=KAFKA_USERNAME=$user \
                  --from-literal=KAFKA_PASSWORD=$pass
              fi
