apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-secret-generator
  namespace: mysql
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: secret-gen
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              if ! kubectl get secret mysql-credentials -n mysql >/dev/null 2>&1; then
                rootpass=$(openssl rand -hex 10)
                userpass=$(openssl rand -hex 8)
                kubectl create secret generic mysql-credentials -n mysql \
                  --from-literal=MYSQL_ROOT_PASSWORD=$rootpass \
                  --from-literal=MYSQL_USER=appuser \
                  --from-literal=MYSQL_PASSWORD=$userpass \
                  --from-literal=MYSQL_DATABASE=appdb
              fi
