apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      nodeSelector:
        role: storgedb
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:5.2
          resources:
            requests:
              cpu: "0.5"
              memory: "1Gi"
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PMA_HOST
              value: mysql-primary.mysql.svc.cluster.local
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_USER
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_PASSWORD
